name: build-and-deploy-repeat-words

on:
  push:
    branches:
      - main
      - feature/actions

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages and release.
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.pagesdeployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    # prepare
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get flutter packages
        run: flutter pub get
    # build
      - name: build web for github pages
        # The --base-ref is defined so that hosting on github pages works.
        run: flutter build web --base-ref /${{ github.event.repository.name }}/
      - name: build apk
        run: flutter build apk
    # release apk
      - name: make release tag
        id: releasetag
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      - name: Upload apk to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.releasetag.outputs.date }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
          draft: false
          prerelease: false
    # upload pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload web artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/web
      - name: Deploy web version to GitHub Pages
        id: pagesdeployment
        uses: actions/deploy-pages@v1
